//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You&apos;ve made astonishing progress! &lt;br/&gt; For your next training session.
        /// </summary>
        internal static string FinishedWorkoutAmazing {
            get {
                return ResourceManager.GetString("FinishedWorkoutAmazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout complete! Good work! &lt;br/&gt; For your next workout.
        /// </summary>
        internal static string FinishedWorkoutGood {
            get {
                return ResourceManager.GetString("FinishedWorkoutGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find user by email..
        /// </summary>
        internal static string NoUserByEmail {
            get {
                return ResourceManager.GetString("NoUserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find user by id..
        /// </summary>
        internal static string NoUserById {
            get {
                return ResourceManager.GetString("NoUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations on your first workout..
        /// </summary>
        internal static string TrainingFirstWorkout {
            get {
                return ResourceManager.GetString("TrainingFirstWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we&apos;ve added some reps to the following exercises : .
        /// </summary>
        internal static string TrainingRepsIncreased {
            get {
                return ResourceManager.GetString("TrainingRepsIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and we have increased the weigth for the following exercises : .
        /// </summary>
        internal static string TrainingWeightIncreasad {
            get {
                return ResourceManager.GetString("TrainingWeightIncreasad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad.
        /// </summary>
        internal static string WeightInvalid {
            get {
                return ResourceManager.GetString("WeightInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error response from wgerAPI:.
        /// </summary>
        internal static string WgerApiError {
            get {
                return ResourceManager.GetString("WgerApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exercise.
        /// </summary>
        internal static string WgerApiResource {
            get {
                return ResourceManager.GetString("WgerApiResource", resourceCulture);
            }
        }
    }
}
